###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
# @Author   :   Tony Guntharp
# @Date     :   07/08/2017
###############################################################################

homeassistant:
  name: Damage Labs
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  elevation: 10
  unit_system: imperial
  time_zone: America/Los_Angeles
  packages: !include_dir_named packages
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend

#introduction:

# Enables the frontend
frontend: !include ./configuration/frontend.yaml

# Enables configuration UI
config:
discovery:
  ignore: 
    - philips_hue
    - dconz  

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ui_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
recorder:

# Track the sun
sun:

sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://10.0.0.13:3218

mqtt:
  broker: m13.cloudmqtt.com
  port: 18143
  client_id: home-assistant
  keepalive: 60
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password

switch:
  - platform: mqtt
    name: "s20-1"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "s20-2"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 100
    waypoints: true

remote:
  - platform: harmony
    name: Living Room 
    activity: Watch TV

#device_tracker:
#  - platform: snmp
#    host: 10.0.0.3
#    baseoid: 1.3.6.1.2.1.1.1.0


media_player:
  - platform: roku

august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

#sensor:
#  - platform: google_wifi

binary_sensor:
  - platform: iss

camera:
  - platform: generic
    name: ISS
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
    limit_refetch_to_url_change: true
