###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
# @Author   :   Tony Guntharp
# @Date     :   07/08/2017
###############################################################################

homeassistant:
  name: Damage Labs
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  elevation: 10
  unit_system: imperial
  time_zone: America/Los_Angeles
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ui_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret


