### SENSORS ###
- platform: mqtt
  state_topic: "owntracks/pixelxl/pixelxl"
  name: "PixelXL Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/pixelxl/pixelxl"
  name: "Latitude"
  value_template: "{{ value_json.lat }}"

- platform: mqtt
  state_topic: "owntracks/pixelxl/pixelxl"
  name: "Longitude"
  value_template: "{{ value_json.lon }}"

- platform: steam_online
  api_key: !secret steam_client_id
  accounts: 
    - 76561198024913711

- platform: speedtest
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload

##################################
####     TIME/DATE            ####
##################################

- platform: worldclock
  time_zone: America/Los_Angeles
  name: 'Half Moon Bay'     
- platform: worldclock
  time_zone: America/New_York
  name: 'New York'
- platform: worldclock
  time_zone: Etc/UTC
  name: 'UTC'
- platform: worldclock
  time_zone: Europe/London
  name: 'London'
- platform: worldclock
  time_zone: Europe/Zurich
  name: 'Zurich'
- platform: worldclock
  time_zone: Asia/Kolkata
  name: 'India'

- platform: wemo
  static:
    - 10.0.0.176

- platform: apple_tv 
  host: 10.0.0.4

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: since_last_boot
    - type: last_boot

- platform: cpuspeed

- platform: coinmarketcap
  currency:
   - litecoin
   - bitcoin
            #          - ethereum  

  #- platform: bitcoin
  # display_options:
  #- exchangerate
  #- trade_volume_btc


- platform: darksky
  api_key: !secret darksky_client_id
  monitored_conditions:
   - summary
   - temperature
   - apparent_temperature
   - wind_speed
   - humidity
   - visibility
   - nearest_storm_distance

